#!/usr/bin/env node

var stdin = process.openStdin();

var data = "";
stdin.on('data', function(chunk) {
  data += chunk;
});
stdin.on('end', function() {
  data = data.replace(/require/g, 'brqre');
  data = data.replace(/brqre\((\'|\").+/g, function (match) {
    if (~match.indexOf('./')) {
      return match;
    }
    else {
      return match.replace('brqre', 'require');
    }
  });

  console.log(data);
});
